"""add cv customized to applications

Revision ID: 0cda56f8800d
Revises: dc47679550fb
Create Date: 2026-08-24 19:13:37.869263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cda56f8800d'
down_revision: Union[str, Sequence[str], None] = 'dc47679550fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cv_customized', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cv_customized')
    # ### end Alembic commands ###
