"""create applications table

Revision ID: 15246dbd38dc
Revises: 64fd3b0dab90
Create Date: 2026-08-12 14:37:00.551154

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15246dbd38dc"
down_revision: str | Sequence[str] | None = "64fd3b0dab90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_offer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                "interview",
                "technical interview",
                "offer",
                "rejected",
                "withdrawn",
                name="application_status_enum",
            ),
            server_default="applied",
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_offer_id"], ["job_offers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_job_offer_id"),
        "applications",
        ["job_offer_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_applications_status"), "applications", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_status"), table_name="applications")
    op.drop_index(op.f("ix_applications_job_offer_id"), table_name="applications")
    op.drop_table("applications")
    sa.Enum(name="application_status_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
