"""create job offers table

Revision ID: a8a6345894a3
Revises: 5e2a9e543241
Create Date: 2026-07-28 15:17:11.382384

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8a6345894a3"
down_revision: str | Sequence[str] | None = "5e2a9e543241"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "work_mode",
            sa.Enum("remote", "hybrid", "on_site", name="work_mode_enum"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "applied",
                "interview",
                "technical_interview",
                "offer",
                "rejected",
                "withdrawn",
                name="job_offer_status_enum",
            ),
            server_default="saved",
            nullable=False,
        ),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_offers_company_id"), "job_offers", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_offers_location"), "job_offers", ["location"], unique=False
    )
    op.create_index(
        op.f("ix_job_offers_status"), "job_offers", ["status"], unique=False
    )
    op.create_index(op.f("ix_job_offers_title"), "job_offers", ["title"], unique=False)
    op.create_index(
        op.f("ix_job_offers_work_mode"), "job_offers", ["work_mode"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_offers_work_mode"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_title"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_status"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_location"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_company_id"), table_name="job_offers")
    op.drop_table("job_offers")

    sa.Enum(name="job_offer_status_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="work_mode_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )


# ### end Alembic commands ###
