"""add external source fields to job offers

Revision ID: dc47679550fb
Revises: 15246dbd38dc
Create Date: 2026-08-17 19:53:04.909806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc47679550fb'
down_revision: Union[str, Sequence[str], None] = '15246dbd38dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('job_offers', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_job_offers_source'), 'job_offers', ['source'], unique=False)
    op.create_unique_constraint('uq_job_offers_source_external_id', 'job_offers', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_offers_source_external_id', 'job_offers', type_='unique')
    op.drop_index(op.f('ix_job_offers_source'), table_name='job_offers')
    op.drop_column('job_offers', 'external_id')
    op.drop_column('job_offers', 'source')
    # ### end Alembic commands ###
